# Exercícios Python e Numpy

O objetivo desse notebook é ajudar na fixação dos conteúdos que passamos na aula de Python e Numpy. Sabemos que acabamos passando meio rápido durante a aula, então o objetivo aqui é conseguir treinar os conceitos para você conseguir usa-los na prática mais tarde.

Qualquer dúvida pode ficar a vontade para perguntar no Slack ou diretamente para gente, vamos ficar felizes em ajudar :)

## Python

Aqui na parte de Python vamos passar por algumas das principais coisas que você precisa saber, é claro que não colocamos tudo de importante da linguagem, só o mais necessário.

### Variáveis

In [0]:
# Declare uma variavel chamada a e atribua o valor 10 a ela
a = 10

In [2]:
# Imprime essa variavel que você acabou de criar
print(a)

10


In [0]:
# Crie uma outra variavel b que recebe o valor de a so que como string
b = str(a)

In [0]:
# Combine sua variavel b a variavel abaixo para obter a string "Hello 10" em uma variavel d
c = "Hello "
d = c + b

In [5]:
# Imprima a variável d
print(d)

Hello 10


### Strings

In [0]:
my_str = 'Insira uma frase aqui!'

In [8]:
# Substitua a exclamação da frase por uma interrogação
# (Dica: A funcão altera inplace ou retorna uma copia modificada?)
my_new_str = my_str.replace('!', '?') # A funçao retorna uma cópia modificada
print(my_new_str)

Insira uma frase aqui?


In [9]:
# Crie uma lista "my_words" com cada palavra a frase
my_words = my_new_str.split()
print(my_words)

['Insira', 'uma', 'frase', 'aqui?']


### Listas

In [0]:
lista = [1, 23, 31, 40, 56, 16]

In [11]:
# Faça um for que imprima cada elemento da lista "lista" (Lembre-se que o for em python é um for each)
for numero in lista:
  print(numero)

1
23
31
40
56
16


In [13]:
# Faça um for que imprima o dobro de cada elemento da lista "lista" 
for numero in lista:
  print(2 * numero)

2
46
62
80
112
32


In [15]:
# Gere uma lista chamada "dobro" com o dobro de cada elemento de "lista" usando list comprehension
dobro = [2 * numero for numero in lista]
print(dobro)

[2, 46, 62, 80, 112, 32]


In [17]:
# Crie uma nova lista chamada "pares"
# Faça um for que itetere sobre a lista "lista" e para cada elemento impar coloque ele no fim da lista "pares"
# Imprima a lista "pares"
pares = []
for numero in lista:
  if numero % 2 == 0:
    pares.append(numero)

print(pares)

[40, 56, 16]


In [0]:
lista2 = ['oi', 2, 2.5, 'top', 'python', 45]

In [20]:
# Faça um for pela "lista2" e imprima todos os elementos que são strings (Dica: pesquise pela função type())
for elemento in lista2:
  if type(elemento) == str:
    print(elemento)

oi
top
python


#### Indexando

In [0]:
my_list = [0, 10, 20, 30, 40, 50, 60, 70]

In [24]:
# Selecione o ultimo elemento da lista
my_list[-1]

70

In [27]:
# Selecione do primeiro até o 4 elemento da lista
my_list[:4]

[0, 10, 20, 30]

In [28]:
# Selecione do segundo elemento da lista até o quinto
my_list[1:5]

[10, 20, 30, 40]

In [29]:
# Selecione do primeiro elemento da lista até o penultimo
my_list[:-1]

[0, 10, 20, 30, 40, 50, 60]

### Dicionários

In [0]:
lista = ['a', 'a', 'b', 'a', 'c', 'd', 'e', 'b', 'b', 'c']

In [0]:
# Crie um dicionario que contenha a contagem de cada elemento do vetor
my_dict = {}
for numero in lista:
  if numero in my_dict:
    my_dict[numero] += 1
  else:
    my_dict[numero] = 1

In [32]:
print(my_dict)

{'a': 3, 'b': 3, 'c': 2, 'd': 1, 'e': 1}


### Funções

In [0]:
# Crie uma função soma_elementos() que recebe uma lista e retorna a soma de todos os seus elementos
def soma_elementos(lista):
    soma = 0
    for numero in lista:
      soma += numero
    return soma

In [34]:
soma_elementos([1, 2, 3, 4, 5])

15

In [35]:
soma_elementos([-1, 5, 7, -2])

9

In [0]:
# Crie uma função produto_escalar() que recebe duas listas de tamanho igual e calcula o produto escalar entre elas
# Dica: Utilize a função zip
def produto_escalar(a, b):
  produto_escalar = 0
  for a_i, b_i in zip(a, b):
    produto_escalar += (a_i * b_i)
  return produto_escalar

In [40]:
produto_escalar([1, 2, 3], [0, 4, 7])

29

In [41]:
produto_escalar([10, 20, 40, 1], [23, 4, 2, 1])

391

In [0]:
# Crie uma função par_ou_impar() que recebe um numero n é para cada numero de 1 a n imprime o numero
# seguido de par ou impar, dependendo do que ele seja. Caso o usuário não coloque nada n deve valer 20
# Exemplo: par_ou_impar(4)
#   1 Impar
#   2 Par
#   3 Impar
#   4 Par

def par_ou_impar(n):
  for i in range(1, n + 1):
    if i % 2 == 0:
      print(str(i) + ' Par')
    else:
      print(str(i) + ' Impar')

In [43]:
par_ou_impar(15)

1 Impar
2 Par
3 Impar
4 Par
5 Impar
6 Par
7 Impar
8 Par
9 Impar
10 Par
11 Impar
12 Par
13 Impar
14 Par
15 Impar


In [0]:
# Crie uma função diga_indice() que recebe uma lista e imprime o indice de cada elemento e em seguida 
# o proprio elemento
# Exemplo: diga_indice(['oi', 'tudo', 'bem'])
#    0 oi
#    1 tudo
#    2 bem
# (DICA: Pesquise pela função enumerate)

def diga_indice(lista):
  for idx, elem in enumerate(lista):
    print(idx, elem)

In [46]:
diga_indice(['1', '2', '3'])

0 1
1 2
2 3


In [47]:
diga_indice(['a', 'b', 'c', 'd', 'e'])

0 a
1 b
2 c
3 d
4 e


## Numpy

O elemento central do numpy são os arrays, então aqui vamos treinar muitas coisas sobre eles

In [0]:
# Importando a biblioteca
import numpy as np

### Arrays

In [0]:
a = np.array([1, 2, 3, 4, 5, 6, 7])

b = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8]])

c = np.zeros((3,4))

In [51]:
# Pense em qual é a shape de cada um dos arrays acima
# Depois de pensar imprima cada um deles para conferir sua resposta
print(a.shape)
print(b.shape)
print(c.shape)

(7,)
(2, 4)
(3, 4)


In [52]:
# Crie um array de uma dimenção com 20 elementos inteiros aletórios entre 0 e 23
my_random_array = np.random.randint(24, size=(20))
print(my_random_array)

[15  9  3  0 14 15 16 22 19 16 12  8 13  6  3 10 19  3  2  3]


In [53]:
# Crie um array de uns com shape (4, 5)
my_array = np.ones((4, 5))
print(my_array)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [54]:
# Crie um array shape (4, 2) onde cada entrada vale 77
# (Dica: Talvez vc tenha que usar uma multiplicação)
my_array = np.ones((4, 2)) * 77
print(my_array)

[[77. 77.]
 [77. 77.]
 [77. 77.]
 [77. 77.]]


In [58]:
# Gere um array chamado my_sequence com os numeros 0, 10, 20, 30, ..., 90, 100
my_array = np.arange(0, 110, 10)
print(my_array)

[  0  10  20  30  40  50  60  70  80  90 100]


### Indexando

In [59]:
my_array = np.random.randint(50, size=(15,))
print(my_array)

[ 8 48 21 20 33 47 22 46 31  1 16  8 43  3  1]


In [60]:
# Selecione todos os elementos entre o quinto e o decimo primeiro (intervalo fechado)
my_array[4:11]

array([33, 47, 22, 46, 31,  1, 16])

In [61]:
# Selecione todos os elementos maiores que 20
my_array[my_array > 20]

array([48, 21, 33, 47, 22, 46, 31, 43])

In [0]:
my_matrix = np.array([[1, 2, 3, 4],
                      [5, 6, 7, 8],
                      [9, 10, 11, 12],
                      [13, 14, 15, 16]])

In [63]:
# Selecione o elemento na primeira linha da terceira coluna
my_matrix[0, 2]

3

In [64]:
# Selecione o elemento na primeira linha da ultima coluna
my_matrix[0, -1]

4

In [65]:
# Selecione os elementos da matriz para obter o seguinte
# [[6, 7],
#  [10, 11]]
my_matrix[1:3, 1:3]

array([[ 6,  7],
       [10, 11]])

In [68]:
# Selecione os elementos da matriz para obter o seguinte
# [[2, 3, 4],
#  [6, 7, 8]]
my_matrix[:2, 1:]

array([[2, 3, 4],
       [6, 7, 8]])

In [69]:
# Selecione os elementos da ultima coluna inteira
my_matrix[:, -1]

array([ 4,  8, 12, 16])

In [70]:
# Selecione os elementos da 2a linha inteira
my_matrix[1, :]

array([5, 6, 7, 8])

### Operações

In [71]:
my_array = np.random.randint(10, size=(5,))
print(my_array)

[0 1 6 3 3]


In [73]:
# Some 10 a todos os elementos de my_array
my_array_plus10 = my_array + 10
print(my_array_plus10)

[10 11 16 13 13]


In [74]:
# Multiplique todos os elementos de my_array por 4
my_array_times4 = my_array * 4
print(my_array_times4)

[ 0  4 24 12 12]


In [75]:
# Obtenha a soma de todos os elementos de my_array
soma = np.sum(my_array)
print(soma)

13


In [76]:
# Obtenha a média de todos os elementos de my_array
media = np.mean(my_array)
print(media)

2.6


In [79]:
# Obtenha o indice do maior elemento de my_array
idx_maior = np.argmax(my_array)
print(idx_maior)

2


In [81]:
my_array = np.random.randint(10, size=(5,))
my_other_array = np.random.randint(10, size=(10,5))
print(my_array, '\n')
print(my_other_array)

[4 9 2 5 8] 

[[3 8 5 5 3]
 [5 9 1 0 1]
 [6 0 4 4 0]
 [3 5 4 1 4]
 [5 3 0 8 8]
 [2 9 7 6 9]
 [0 8 2 7 4]
 [2 0 0 7 6]
 [1 2 2 3 3]
 [4 9 0 7 5]]


In [83]:
# Some my_array elemento por elemento em cada linha de my_other_array
result_array = my_other_array + my_array
print(result_array)

[[ 7 17  7 10 11]
 [ 9 18  3  5  9]
 [10  9  6  9  8]
 [ 7 14  6  6 12]
 [ 9 12  2 13 16]
 [ 6 18  9 11 17]
 [ 4 17  4 12 12]
 [ 6  9  2 12 14]
 [ 5 11  4  8 11]
 [ 8 18  2 12 13]]


In [84]:
my_array = np.random.randint(10, size=(5,4))
my_other_array = np.random.randint(10, size=(10,5))
print(my_array, '\n')
print(my_other_array)

[[8 9 6 3]
 [3 1 7 7]
 [4 5 3 9]
 [5 6 8 0]
 [0 7 9 3]] 

[[2 5 0 7 4]
 [6 8 6 6 0]
 [8 1 6 9 4]
 [0 8 9 9 0]
 [3 1 3 0 2]
 [6 5 4 9 4]
 [9 3 0 8 2]
 [3 4 2 2 6]
 [4 5 8 2 1]
 [6 4 7 3 5]]


In [85]:
# Faça a multiplicação entre my_other_array e my_array
mult_array = np.dot(my_other_array, my_array)
print(mult_array)

[[ 66  93 139  53]
 [126 128 158 128]
 [136 185 181  97]
 [105 107 155 137]
 [ 39  57  52  49]
 [124 161 191 101]
 [121 146 157  54]
 [ 54  95 122  73]
 [ 89 100 108 122]
 [103 146 154 124]]


In [87]:
# Descubra a soma dos valores de cada linha de my_other_array
# (Dica: Pesquise sobre o atributo axis da função de soma)
soma_linhas = np.sum(my_other_array, axis=1)
print(soma_linhas)

[18 26 28 26  9 28 22 17 20 25]


In [88]:
my_array = np.random.randint(10, size=(5,4))
print(my_array)

[[5 3 0 0]
 [7 3 9 9]
 [9 6 2 0]
 [0 1 9 2]
 [7 0 7 9]]


In [91]:
# Usando reshape transforme a matriz acima em um vetor (Concatendo a linha de baixo na de cima
my_array_vetor = my_array.reshape(-1)
print(my_array_vetor)

[5 3 0 0 7 3 9 9 9 6 2 0 0 1 9 2 7 0 7 9]


In [92]:
np.array([[ 0,  1,  2,  3,  4,  5,  6,  7],
          [ 8,  9, 10, 11, 12, 13, 14, 15]])

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [95]:
# Gere a array anterior usando np.arange e a função reshape
sequencia = np.arange(16)
resultado = sequencia.reshape(2, -1)
print(resultado)

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]]
